name: Cargo build release on push
on: [ push ]

jobs:
  Build-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-shell nix-scripts/cargo-build.nix --pure

      - uses: actions/upload-artifact@v2
        with:
          path: target/release/sg_cli
