name: Rust Codecov
on: [ push ]

jobs:
  Rust-Codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-shell nix-shell/codecov.nix --pure
      - uses: codecov/codecov-action@v2
