name: Rust Codecov
on: [ push ]

jobs:
  Rust-Codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rust Codecov
        uses: maboesanman/rust-codecov@v0
      - run: "cat codecov.json"
